// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4M10qZGypNG0mkPLwD839hTK5su272Ek',
    appId: '1:1093325679731:web:c8911704d1f5e245024e06',
    messagingSenderId: '1093325679731',
    projectId: 'myproject-9acf3',
    authDomain: 'myproject-9acf3.firebaseapp.com',
    storageBucket: 'myproject-9acf3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAct68J7_N3STXBrzwHksKp9K4LCt7VenA',
    appId: '1:1093325679731:android:bfd1e5a9d8872082024e06',
    messagingSenderId: '1093325679731',
    projectId: 'myproject-9acf3',
    storageBucket: 'myproject-9acf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_5c75oQLPR5zsHDVy74Gh4pjLXXaEmSU',
    appId: '1:1093325679731:ios:0771b3bd48b5399e024e06',
    messagingSenderId: '1093325679731',
    projectId: 'myproject-9acf3',
    storageBucket: 'myproject-9acf3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_5c75oQLPR5zsHDVy74Gh4pjLXXaEmSU',
    appId: '1:1093325679731:ios:0e1b88153cb7f1a8024e06',
    messagingSenderId: '1093325679731',
    projectId: 'myproject-9acf3',
    storageBucket: 'myproject-9acf3.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
