class Data {
  static List<String> cities = [
    // Morocco
    'Casablanca, Morocco',
    'Rabat, Morocco',
    'Marrakech, Morocco',
    'Tanger, Morocco',
    'Meknes, Morocco',
    'Fes, Morocco',
    'Agadir, Morocco',
    'Essaouira, Morocco',
    'Chefchaouen, Morocco',
    'Ouarzazate, Morocco',
    'Tetouan, Morocco',
    'El Jadida, Morocco', 'Kenitra, Morocco',
    'Safi, Morocco',
    'Mohammedia, Morocco',
    'Khouribga, Morocco',
    'Nador, Morocco',
    'Settat, Morocco',
    'Al Hoceima, Morocco',
    'Larache, Morocco',
    // United States
    'New York, USA',
    'Los Angeles, USA',
    'Chicago, USA',
    'Houston, USA',
    'Philadelphia, USA',
    'Phoenix, USA',
    'San Antonio, USA',
    'San Diego, USA',
    'Dallas, USA',
    'San Jose, USA',
    'Austin, USA',
    'Jacksonville, USA',
    'San Francisco, USA',
    'Indianapolis, USA',
    'Columbus, USA',
    'Fort Worth, USA',
    'Charlotte, USA',
    'Seattle, USA',
    'Denver, USA',
    'Washington, USA',

    // Canada
    'Toronto, Canada',
    'Montreal, Canada',
    'Vancouver, Canada',
    'Calgary, Canada',
    'Edmonton, Canada',
    'Ottawa, Canada',
    'Quebec City, Canada',
    'Winnipeg, Canada',
    'Hamilton, Canada',
    'London, Canada',

    // United Kingdom
    'London, United Kingdom',
    'Birmingham, United Kingdom',
    'Manchester, United Kingdom',
    'Glasgow, United Kingdom',
    'Liverpool, United Kingdom',
    'Leeds, United Kingdom',
    'Sheffield, United Kingdom',
    'Edinburgh, United Kingdom',
    'Bristol, United Kingdom',
    'Cardiff, United Kingdom',

    // Australia
    'Sydney, Australia',
    'Melbourne, Australia',
    'Brisbane, Australia',
    'Perth, Australia',
    'Adelaide, Australia',
    'Gold Coast, Australia',
    'Newcastle, Australia',
    'Canberra, Australia',
    'Sunshine Coast, Australia',
    'Wollongong, Australia',

    // France
    'Paris, France',
    'Marseille, France',
    'Lyon, France',
    'Toulouse, France',
    'Nice, France',
    'Nantes, France',
    'Strasbourg, France',
    'Montpellier, France',
    'Bordeaux, France',
    'Lille, France',

    // Germany
    'Berlin, Germany',
    'Hamburg, Germany',
    'Munich, Germany',
    'Cologne, Germany',
    'Frankfurt, Germany',
    'Stuttgart, Germany',
    'Düsseldorf, Germany',
    'Dortmund, Germany',
    'Essen, Germany',
    'Leipzig, Germany',

    // Spain
    'Barcelona, Spain',
    'Madrid, Spain',
    'Valencia, Spain',
    'Seville, Spain',
    'Zaragoza, Spain',
    'Málaga, Spain',
    'Murcia, Spain',
    'Palma de Mallorca, Spain',
    'Las Palmas de Gran Canaria, Spain',
    'Bilbao, Spain',
  ];

  static List<String> Industries = [
    "Technology IT",
    'Finance & Insurance',
    "Media",
    'Healthcare & Social Assistance',
    'Administrative & Support Services',
    'Transportation & Warehousing',
    'Accommodation & Food Service',
    'Information & Communication Technology',
    'Real Estate & Rental & Leasing',
    'Professional, Scientific & Technical Services',
    'Chemical & Pharmaceutical Manufacturing',
    'Metal Products Manufacturing',
    'Machinery & Equipment Manufacturing',
    'Construction',
  ];

  static List<String> skills = [
  'Java',
  'Python',
  'JavaScript',
  'SQL',
  'HTML',
  'CSS',
  'React',
  'Angular',
  'Node.js',
  'Spring Framework',
  'Git',
  'RESTful APIs',
  'Database management',
  'Data analysis',
  'Machine learning',
  'Artificial intelligence',
  'Problem-solving',
  'Teamwork',
  'Leadership',
  'Communication',
  'Time management',
  'Creativity',
  'Adaptability',
  'Critical thinking',
  'Customer service',
  'Project management',
  'Sales skills',
  'Financial analysis',
  'Statistical analysis',
  'Graphic design',
  'UI/UX design',
  'Social media management',
  'Content creation',
  'Digital marketing',
  'Search engine optimization (SEO)',
  'Copywriting',
  'Presentation skills',
  'Microsoft Office Suite',
  'Adobe Creative Suite',
  'Figma',
  'Sketch',
  'Analytical skills',
  'Attention to detail',
  'Interpersonal skills',
  'Negotiation',
  'Decision-making',
  'Writing skills',
  'PHP',
  'C++',
  'C#',
  'Ruby',
  'Swift',
  'Kotlin',
  'TypeScript',
  'Laravel',
  'Django',
  'Flask',
  'Vue.js',
  'Express.js',
  'MongoDB',
  'Firebase',
  'Docker',
  'Kubernetes',
  'Agile methodologies',
  'Scrum',
  'Kanban',
  'DevOps',
  'Cybersecurity',
  'Network administration',
  'Cloud computing',
  'Amazon Web Services (AWS)',
  'Microsoft Azure',
  'Google Cloud Platform (GCP)',
  'Linux',
  'Windows Server',
  'IT troubleshooting',
  'Frontend development',
  'Backend development',
  'Mobile app development',
  'Web design',
  'User research',
  'Data visualization',
  'Database administration',
  'SEO analysis',
  'Email marketing',
  'Brand management',
  'Market research',
  'Business development',
  'Financial planning',
  'Risk management',
  'Supply chain management',
  'Logistics',
  'Quality assurance',
  'Human resources management',
  'Employee training',
  'Conflict resolution',
  'Public speaking',
  'Event planning',
  'Foreign language proficiency',
];
}
